name: CI
on:
  push:
    branches: [main, master]

permissions:
  contents: read

jobs:
  ci:
    # yamllint disable rule:line-length
    uses: nikolareljin/ci-helpers/.github/workflows/java.yml@b5c8ac82ce3ce84f30ca3aa389c9075075dcab6a
    # yamllint enable rule:line-length
    with:
      java_version: "17"
      # Android projects usually use gradlew assembleDebug for build
      build_command: "./gradlew assembleDebug"
      # And gradlew test for unit tests
      test_command: "./gradlew test"
      # Use Gradle lint instead of default Maven checkstyle
      lint_command: "./gradlew lint"
